name: Make release
on:
  # workflow_run:
  #   workflows: ["lint"]
  #   types:
  #     - completed
  push:
    tags:
      - v**
jobs:
  make-build:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }} && startsWith(github.event.head_commit.message, 'chore(bump)')
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Get Commit SHA and Tag
        run: .github/workflows/release_name.bat %GITHUB_SHA%
        shell: cmd
      - name: Check if it should make a build
        run : |
          '${{ github.sha }}' -notlike "~*"

      - name: Make release build
        run: cargo build --release
        if: success()
      - name: Configure github bot
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
        shell: cmd

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body: |
            Version ${{ env.TAG }} automated release
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/event-bot.exe
          asset_name: event-bot.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
